INSERT INTO varieties (plant_id, name)
SELECT p.id, v.name
FROM (VALUES
  ('tomate', 'Big Beef'), ('tomate', 'Celebrity'), ('tomate', 'Beefsteak'),
  ('tomate', 'Cherokee Purple'), ('tomate', 'Sungold'), ('tomate', 'Roma'),
  ('tomate', 'San Marzano'), ('tomate', 'Mémé de Beauce'), ('tomate', 'Manitoba'),
  ('tomate', 'Moskvich'), ('tomate', 'Brandywine'), ('tomate', 'Ananas'),
  ('tomate', 'Early Cherry'), ('tomate', 'Gold Nugget'), ('tomate', 'Siletz'),
  ('tomate', 'Québec No 13'), ('tomate', 'Précociébec'), ('tomate', 'Canabec Rose'),
  ('tomate', 'Petit Moineau'), ('tomate', 'Cerise'), ('tomate', 'Coeur de boeuf'),
  ('tomate', 'Noire de Crimée'),
  ('piment-poivron', 'California Wonder'), ('piment-poivron', 'King of the North'),
  ('piment-poivron', 'Doe Hill'), ('piment-poivron', 'Red Marconi'),
  ('piment-poivron', 'Purple Beauty'), ('piment-poivron', 'Chocolate'),
  ('piment-poivron', 'Ace'), ('piment-poivron', 'Petit Marseillais'),
  ('piment-poivron', 'Jalapeño'), ('piment-poivron', 'Cayenne'),
  ('piment-poivron', 'Habanero'), ('piment-poivron', 'Hungarian Hot Wax'),
  ('piment-poivron', 'Serrano'), ('piment-poivron', 'Poblano'),
  ('piment-poivron', 'Thaï'), ('piment-poivron', 'Anaheim'),
  ('piment-poivron', 'Scotch Bonnet'), ('piment-poivron', 'd''Espelette'),
  ('piment-poivron', 'Shishito'),
  ('aubergine', 'Black Beauty'), ('aubergine', 'Diamond'),
  ('aubergine', 'Little Finger'), ('aubergine', 'Ping Tung Long'),
  ('concombre', 'Marketmore 76'), ('concombre', 'Tante Alice'),
  ('concombre', 'Spacemaster'), ('concombre', 'Citron'),
  ('concombre', 'National Pickling'), ('concombre', 'Diva'),
  ('concombre', 'Straight Eight'), ('concombre', 'Suyo Long'),
  ('concombre', 'Green Finger'),
  ('courgette', 'Black Beauty'), ('courgette', 'Costata Romanesco'),
  ('courgette', 'Ronde de Nice'), ('courgette', 'Gold Rush'),
  ('courgette', 'Genovese'), ('courgette', 'Pâtisson'),
  ('courgette', 'Crookneck'), ('courgette', 'Straightneck'),
  ('citrouille-courge-hiver', 'Butternut'), ('citrouille-courge-hiver', 'Spaghetti'),
  ('citrouille-courge-hiver', 'Buttercup'), ('citrouille-courge-hiver', 'Acorn'),
  ('citrouille-courge-hiver', 'Potimarron'), ('citrouille-courge-hiver', 'Delicata'),
  ('citrouille-courge-hiver', 'Hubbard'), ('citrouille-courge-hiver', 'Black Futsu'),
  ('citrouille-courge-hiver', 'Canadian Crookneck'), ('citrouille-courge-hiver', 'Citrouille'),
  ('melon', 'Melon de Montréal'), ('melon', 'Melon d''Oka'),
  ('melon', 'Minnesota Midget'), ('melon', 'Charentais'),
  ('melon', 'Sugar Baby'), ('melon', 'Crème de Saskatchewan'),
  ('haricot-nain', 'Provider'), ('haricot-nain', 'Maxibel'),
  ('haricot-nain', 'Pencil Pod Black'), ('haricot-nain', 'Rocquencourt'),
  ('haricot-nain', 'Royal Burgundy'), ('haricot-nain', 'Fin de Bagnol'),
  ('haricot-nain', 'Black Valentine'), ('haricot-nain', 'Fortin'),
  ('haricot-nain', 'Thibodeau'),
  ('haricot-grimpant', 'Monte Gusto'), ('haricot-grimpant', 'Rattlesnake'),
  ('haricot-grimpant', 'Kilomètre'), ('haricot-grimpant', 'Grand-mère Dinel'),
  ('pois', 'Sugar Snap'), ('pois', 'Sugar Ann'), ('pois', 'Green Arrow'),
  ('pois', 'Lincoln'), ('pois', 'Petit Provençal'), ('pois', 'Oregon Sugar Pod'),
  ('pois', 'Alaska'),
  ('mais', 'Peaches & Cream'), ('mais', 'Golden Bantam'), ('mais', 'Illini Gold'),
  ('mais', 'Blue Hopi'), ('mais', 'Popcorn'),
  ('carotte', 'Scarlet Nantes'), ('carotte', 'Danvers 126'), ('carotte', 'Imperator'),
  ('carotte', 'Chantenay'), ('carotte', 'Touchon'), ('carotte', 'Purple Haze'),
  ('carotte', 'Bolero'),
  ('betterave', 'Detroit Dark Red'), ('betterave', 'Chioggia'), ('betterave', 'Cylindra'),
  ('betterave', 'Bull''s Blood'), ('betterave', 'Crosby''s Egyptian'), ('betterave', 'Golden'),
  ('oignon', 'Espagnol jaune'), ('oignon', 'Stuttgarter'), ('oignon', 'Patterson'),
  ('oignon', 'Red Burgundy'), ('oignon', 'Walla Walla'), ('oignon', 'Blanc'),
  ('radis-de-printemps', 'Cherry Belle'), ('radis-de-printemps', 'French Breakfast'),
  ('radis-de-printemps', 'Easter Egg'), ('radis-de-printemps', 'Watermelon'),
  ('radis-de-printemps', 'Champion'), ('radis-de-printemps', 'Hailstone'),
  ('radis-hiver', 'Daikon'), ('radis-hiver', 'Rose de Chine'), ('radis-hiver', 'Noir d''hiver'),
  ('laitue', 'Buttercrunch'), ('laitue', 'Iceberg'), ('laitue', 'Parris Island Cos'),
  ('laitue', 'Feuille de chêne'), ('laitue', 'Feuille de chêne rouge'),
  ('laitue', 'Black Seeded Simpson'), ('laitue', 'Grand Rapids'),
  ('laitue', 'Merveille des 4 saisons'), ('laitue', 'Lollo Rossa'),
  ('laitue', 'Sucrine'), ('laitue', 'Merlot'),
  ('epinard', 'Bloomsdale Long Standing'), ('epinard', 'Géant d''hiver'), ('epinard', 'Verdil'),
  ('chou-frise', 'Lacinato'), ('chou-frise', 'Rouge de Russie'), ('chou-frise', 'Frisé vert'),
  ('chou-frise', 'Dwarf Blue Curled'), ('chou-frise', 'Winterbor'), ('chou-frise', 'Redbor'),
  ('chou-pomme', 'Copenhagen Market'), ('chou-pomme', 'Golden Acre'), ('chou-pomme', 'Red Acre'),
  ('chou-pomme', 'Savoy'), ('chou-pomme', 'January King'), ('chou-pomme', 'Napa'),
  ('brocoli', 'De Cicco'), ('brocoli', 'Waltham 29'), ('brocoli', 'Calabrese'),
  ('brocoli', 'Purple Peacock'), ('brocoli', 'Green Magic'),
  ('celeri', 'Utah'), ('celeri', 'Tall Utah 52-70'), ('celeri', 'Céleri-rave'),
  ('basilic', 'Genovese'), ('basilic', 'Mammouth'), ('basilic', 'Purple Ruffles'),
  ('basilic', 'Thaï'), ('basilic', 'Citron'), ('basilic', 'Perse'),
  ('persil', 'Plat italien'), ('persil', 'Frisé'),
  ('coriandre', 'Commune'), ('coriandre', 'Santo'), ('coriandre', 'Vietnamienne'),
  ('ciboulette', 'Commune'),
  ('ciboulette-chinoise', 'Ail'),
  ('aneth', 'Bouquet'), ('aneth', 'Mammouth'), ('aneth', 'Fernleaf'),
  ('origan', 'Grec'), ('origan', 'Doré'), ('origan', 'Commun'),
  ('sauge-officinale', 'Officinale'), ('sauge-officinale', 'Tricolore'), ('sauge-officinale', 'Pourpre'),
  ('thym', 'Commun'), ('thym', 'Citron'), ('thym', 'Serpolet')
) AS v(slug, name)
JOIN plants p ON p.slug = v.slug
ON CONFLICT (plant_id, name) DO NOTHING;
